# Generated by Django 5.0.6 on 2026-01-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='last_notified_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='advance_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved (Payment Pending)'), ('PAID', 'Paid (Confirmed)'), ('DENIED', 'Denied')], default='PENDING', max_length=20),
        ),
    ]
