# Generated by Django 5.0.6 on 2026-01-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_booking_last_notified_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_notified_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
