# Generated by Django 5.0.6 on 2026-01-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_booking_last_notified_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved (Payment Pending)'), ('PAID', 'Paid (Waiting Admin Confirmation)'), ('CONFIRMED', 'Confirmed ✅'), ('DENIED', 'Denied')], default='PENDING', max_length=20),
        ),
    ]
